### ISSUE TITLE
EBankingJFrame: SQL Error

### ISSUE THREAD

**Issue by DigitalCoffee** [devinc13/SENG426ECheque#5]
Defect: SQL error creating cheque cancel flag

Solution: Explain the error to the user

**Comment by devinc13** [comment]
"Cannot add or update a child row: a foreign key constraint fails (`ebank`.`cancelledcheque`, CONSTRAINT `cancelledcheque_ibfk_1` FOREIGN KEY (`chequeID`) REFERENCES `echequeout` (`chequeID`))"

This means we can't cancel a cheque that hasn't been sent. Make sure we convey this to the user.

**Comment by kahunalu** [comment]
This cheque was not sent (unless cheques are sent on creation than nvm this haha) and I was able to "cancel" it. Idk what cancelling does since I am still able to see the cheque in "My Cheques"

![chequecancelled](https://cloud.githubusercontent.com/assets/7245192/17117720/52bbd61e-5272-11e6-90a3-7a92ec36ed9e.PNG)

**Comment by devinc13** [comment]
Running locally on my computer creates this error, since I can create a clean database. Using the lab database that we can't access, it doesn't seem to have an issue creating a cancelled cheque when the chequeID isn't in the echequeout table. Can't debug without access to DB, closing as not an issue at the moment, since if the error is encountered, it handles it, and if it is working in the lab db as expected, it's not a defect.
